language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: gerardo+npm@gaderas.com
  api_key:
    secure: dmR+zGBL+llWInxaUPAwv+dqQKX26OOwswhhSC7Gt/z0M5WcRIcANkLniMDd5MI4CnyQWjJe2cAjISEDKNVRvdzkYgG/mER85FNot1VjtYOzTLchK3O724IjkoqX9+4tu83xZhhxNgkKwN2uZRP/4pKo3lI5/WJEIbYt2G5ZMcs=
  on:
    tags: true
    repo: sanx/dendro
    all_branches: true

